stages:
  - build
  - test

variables:
  IMAGE_NAME: "order-service"
  IMAGE_TAG: "latest"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" --target builder .

test:
  stage: test
  script:
    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" --target tester .