stages:
  - build
  - test

# variables:
#   IMAGE_NAME: "order-service"
#   IMAGE_TAG: "latest"
#   DOCKER_TLS_CERTDIR: ""
#   DOCKER_HOST: "tcp://docker:2375"  # Указать, где находится Docker daemon

build:
  stage: build
  script:
    - docker build -t order-service_build --target builder .

test:
  stage: test
  script:
    - docker build -t order-service_test --target tester .