FROM golang:1.24

RUN apt-get update && apt-get install -y \
    make \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="${PATH}:$(go env GOPATH)/bin"

WORKDIR /app

COPY . .

RUN make setup 

EXPOSE 8080:8080
EXPOSE 50051:50051

CMD ["./bin/order-server"]
# CMD ["bash"]