services:
  db:
    image: postgres:15
    container_name: Postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    ports:
      - "5430:5432"
    volumes:
      - postgres:/data/postgres
volumes:
  postgres: