GRPC_PORT: 50051
HTTP_PORT: 8080
POSTGRES:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASS: postgres
  POSTGRES_DB: test_db
  POSTGRES_SSLMODE: disable

  POSTGRES_MAX_CONN: 10
  POSTGRES_MIN_CONN: 5
