GRPC_PORT: 50051
HTTP_PORT: 8080
ENV: local
POSTGRES:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: admin
  POSTGRES_PASS: admin
  POSTGRES_DB: test_db
  POSTGRES_SSLMODE: disable

  POSTGRES_MAX_CONN: 10
  POSTGRES_MIN_CONN: 5
REDIS:
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_PASS: admin
  REDIS_DB: 0